[window]
dimensions = { columns = 100, lines = 28 }
padding = { x = 10, y = 10 }
decorations = "None"

[font]
normal = { family = "JetBrainsMono NF", style = "Regular"}

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "S", mods = "Control", action = "None" }
]

# Colors (Terminal.app)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#b6b6b6'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#990000'
green   = '#00a600'
yellow  = '#999900'
blue    = '#0000b2'
magenta = '#b200b2'
cyan    = '#00a6b2'
white   = '#bfbfbf'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#e50000'
green   = '#00d900'
yellow  = '#e5e500'
blue    = '#0000ff'
magenta = '#e500e5'
cyan    = '#00e5e5'
white   = '#e5e5e5'
