#!/usr/bin/env bash

STATE=$(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .capsLock')

if [[ "$STATE" == "true" ]]; then
  notify-send -c on -i input-keyboard \
    "Caps Lock" "Enabled"
else
  notify-send -c off -i input-keyboard \
    "Caps Lock" "Disabled"
fi
