#!/bin/sh
STEP=5
LIMIT=1.5   # set to 1 if you don’t want >100%

case "$1" in
  up)   wpctl set-volume -l $LIMIT @DEFAULT_AUDIO_SINK@ ${STEP}%+ ;;
  down) wpctl set-volume -l $LIMIT @DEFAULT_AUDIO_SINK@ ${STEP}%- ;;
  mute) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
  *) exit 1 ;;
esac

OUT="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
echo "$OUT" | grep -q MUTED && echo 0 > /tmp/wobpipe || echo "$OUT" | awk '{print int($2*100)}' > /tmp/wobpipe
