syntax on
set tabstop=2 softtabstop=2 shiftwidth=2
set expandtab
set number ruler
set autoindent smartindent
syntax enable
filetype plugin indent on
set mouse=a
set clipboard=unnamedplus
set viminfofile=$XDG_STATE_HOME/vim/viminfo
