general {
    lock_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# dim
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 1
    on-resume = brightnessctl -r
}

# lock
listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

# dpms off
listener {
    timeout = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

# suspend
listener {
    timeout = 600
    on-timeout = doas -n sh -c 'echo mem > /sys/power/state'
}
