# monitors
monitorrule=make:Dell Inc.,model:DELL P2425H,serial:HHNRC74,width:1920,height:1080,refresh:100,x:0,y:0,scale:1
monitorrule=name:^eDP-1$,x:0,y:1080,scale:1

# startup
exec-once=sh -c 'umask 077; printf "%s\n" "$DBUS_SESSION_BUS_ADDRESS" > "$XDG_RUNTIME_DIR/dbus-address"'
exec-once=swayidle
exec-once=gentoo-pipewire-launcher
exec-once=foot -s
exec-once=mako
exec-once=swaybg -i ~/.local/share/wallpapers/supermassive_blackhole.png -m fill
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=waybar

# Animation
animations=0
layer_animations=0

# Misc
no_border_when_single=1
smartgaps=1
cursor_theme=macOS

# Keyboard
xkb_rules_options=caps:escape

# Mouse
mouse_accel_speed=-0.1
trackpad_natural_scrolling=1
trackpad_accel_speed=0.5
drag_lock=0

# Appearance
gappih=0
gappiv=0
gappoh=0
gappov=0
borderpx=1

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

# Key Bindings

# reload config
bind=SUPER,r,reload_config

# menu and terminal
bind=SUPER,Return,spawn,footclient
bind=SUPER,b,spawn,librewolf
bind=SUPER,d,spawn,tofi-drun
bind=SUPER,s,spawn_shell,wayfreeze --hide-cursor --after-freeze-cmd 'grim -l 0 -g "$(slurp)" - | wl-copy; killall wayfreeze'
bind=SUPER,v,spawn_shell,cliphist list | sed 's/\t/ /' | tofi --prompt-text 'clipboard: ' | sed -E 's/^([0-9]+) /\1\t/' | cliphist decode | wl-copy
bind=SUPER,period,spawn,~/.config/mango/scripts/emoji.sh
bind=SUPER,z,spawn,env HOME=/home/hamzah/.local/share/vesktop vesktop-bin
bind=SUPER,w,spawn_shell,pkill -x waybar; exec waybar
bind=SUPER,less,spawn,pkill -SIGUSR1 waybar
bind=SUPER,c,spawn_shell,footclient --app-id qalcterm sh -c 'qalc; exec "$SHELL"'
bind=SUPER,t,spawn_shell,footclient --app-id taskterm sh -c 'task limit:20; exec "$SHELL"'

# hardware
bindl=NONE,XF86AudioRaiseVolume,spawn,~/.config/mango/scripts/volume.sh up
bindl=NONE,XF86AudioLowerVolume,spawn,~/.config/mango/scripts/volume.sh down
bindl=NONE,XF86AudioMute,spawn,~/.config/mango/scripts/volume.sh mute
bindl=NONE,XF86MonBrightnessDown,spawn,brightnessctl -n set 5%-
bindl=NONE,XF86MonBrightnessUp,spawn,brightnessctl set 5%+
bind=NONE,XF86TouchpadOff,spawn,notify-send -c off -i input-touchpad "Touchpad" "Disabled"
bind=NONE,XF86TouchpadOn,spawn,notify-send -c on -i input-touchpad "Touchpad" "Enabled"
bind=NONE,XF86Sleep,spawn_shell,(pidof -q waylock || waylock -fork-on-lock -init-color 0x000000 -input-color 0x202020 -fail-color 0x300000) && doas -n sh -c 'echo mem > /sys/power/state'
bind=NONE,XF86PowerOff,spawn,waylock -init-color 0x000000 -input-color 0x202020 -fail-color 0x300000

# exit
bind=SUPER,m,quit
bind=SUPER,q,killclient,

# switch window focus
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

bind=SUPER,f,togglemaximizescreen

mousebind=SUPER,btn_left,moveresize,curmove
gesturebind=none,left,3,viewtoright
gesturebind=none,right,3,viewtoleft

windowrule=isfloating:1,width:900,height:600,appid:^qalcterm$
windowrule=isfloating:1,width:900,height:600,appid:^taskterm$
