# ==========================================
# windows and workspaces
# ==========================================

# workspace appearance
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule {
    name = no-gaps-wtv1
    match:float = false
    match:workspace = w[tv1]

    border_size = 0
    rounding = 0
}

windowrule {
    name = no-gaps-f1
    match:float = false
    match:workspace = f[1]

    border_size = 0
    rounding = 0
}

# generic rules
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# app-specific rules
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = copyq-popup
    match:class = com.github.hluk.copyq

    float = yes
    center = yes
    pin = yes
    size = 900 900
}

windowrule {
    name = taskwarrior
    match:class = taskterm

    float = yes
    center = yes
    size = 900 600
}

windowrule {
    name = yazi
    match:class = yaziterm

    float = yes
    center = yes
    size = 1500 800
}

windowrule {
    name = qalc
    match:class = qalcterm

    float = yes
    center = yes
    size = 900 600
}
