# ==========================================
# hyprland config loader
# ==========================================
# small entrypoint that sources conf/

source = ~/.config/hypr/conf/session.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/rules.conf
