# ==========================================
# input
# ==========================================

# keyboard and pointer defaults
input {
    sensitivity = 0.5
    touchpad:natural_scroll = true
}

# three-finger workspace swipe
gesture = 3, horizontal, workspace
